FROM nvidia/cuda

# RUN pip3 install torch==0.4.1 torchvision==0.2.1 cpuonly
RUN pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install -U setuptools
RUN pip install scipy==1.1.0 --use-deprecated=legacy-resolver
RUN pip install opencv-python==3.4.2.17
RUN pip install scikit-image==0.14.2 --use-deprecated=legacy-resolver

WORKDIR /app

COPY . .

CMD [ "python", "test.py", "--trained_model=craft_model/weights/craft_mlt_25k.pth", "--test_folder=testing", "--cuda=False"]